// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDJN5Hzw0pjP1jV_-DpnHB5M-jBnYzhvY',
    appId: '1:947746393097:web:b62e15d1170ead02d33cd8',
    messagingSenderId: '947746393097',
    projectId: 'planify-malak-2026-fd34c',
    authDomain: 'planify-malak-2026-fd34c.firebaseapp.com',
    storageBucket: 'planify-malak-2026-fd34c.firebasestorage.app',
    measurementId: 'G-MQWTQMHZ7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnsUsekkLbBcN802eVm9TLVUMZu7bo_SY',
    appId: '1:947746393097:android:8144fa2a6bd09b8bd33cd8',
    messagingSenderId: '947746393097',
    projectId: 'planify-malak-2026-fd34c',
    storageBucket: 'planify-malak-2026-fd34c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzSCMn_JMYpHPUlJQvvf7NrIrmfaFpubQ',
    appId: '1:947746393097:ios:7156f0b670864147d33cd8',
    messagingSenderId: '947746393097',
    projectId: 'planify-malak-2026-fd34c',
    storageBucket: 'planify-malak-2026-fd34c.firebasestorage.app',
    androidClientId: '947746393097-g4627eareemi0cbe52m43asqrh94hgut.apps.googleusercontent.com',
    iosClientId: '947746393097-4kvi2hrllcuc0rpbn4suq7l9fnsk9a09.apps.googleusercontent.com',
    iosBundleId: 'com.example.planify',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzSCMn_JMYpHPUlJQvvf7NrIrmfaFpubQ',
    appId: '1:947746393097:ios:7156f0b670864147d33cd8',
    messagingSenderId: '947746393097',
    projectId: 'planify-malak-2026-fd34c',
    storageBucket: 'planify-malak-2026-fd34c.firebasestorage.app',
    androidClientId: '947746393097-g4627eareemi0cbe52m43asqrh94hgut.apps.googleusercontent.com',
    iosClientId: '947746393097-4kvi2hrllcuc0rpbn4suq7l9fnsk9a09.apps.googleusercontent.com',
    iosBundleId: 'com.example.planify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDJN5Hzw0pjP1jV_-DpnHB5M-jBnYzhvY',
    appId: '1:947746393097:web:9c97599257f9f552d33cd8',
    messagingSenderId: '947746393097',
    projectId: 'planify-malak-2026-fd34c',
    authDomain: 'planify-malak-2026-fd34c.firebaseapp.com',
    storageBucket: 'planify-malak-2026-fd34c.firebasestorage.app',
    measurementId: 'G-DLJFWC422V',
  );
}
